<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AsiaGamingTablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'code' => 'SB67',
                'name' => 'Wild Koi',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB67_EN.png',
            ],
            [
                'code' => 'SB72',
                'name' => 'Royal Gems',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB72_EN.png',
            ],
            [
                'code' => 'SB68',
                'name' => 'Pirates Ahoy!',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB68_EN.png',
            ],
            [
                'code' => 'SB70',
                'name' => 'Animal Fun Park',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB70_EN.png',
            ],
            [
                'code' => 'SB73',
                'name' => 'Treasure Party',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB73_EN.png',
            ],
            [
                'code' => 'WH58',
                'name' => 'Lucky Express',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH58_EN.png',
            ],
            [
                'code' => 'SB66',
                'name' => 'Kong Invasion',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB66_EN.png',
            ],
            [
                'code' => 'SB62',
                'name' => 'Wild Gods',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB62_EN.png',
            ],
            [
                'code' => 'SB65',
                'name' => 'Knight and Dragon',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB65_EN.png',
            ],
            [
                'code' => 'SC07',
                'name' => 'Gold Class Deluxe',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SC07_EN.png',
            ],
            [
                'code' => 'WH48',
                'name' => 'Pillar of Fortune',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH48_EN.png',
            ],
            [
                'code' => 'TG04',
                'name' => 'Let it ride',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/TG04_EN.png',
            ],
            [
                'code' => 'SB64',
                'name' => 'Lucky Riches',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB64_EN.png',
            ],
            [
                'code' => 'WH56',
                'name' => 'Mermaid Treasure',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH56_EN.png',
            ],
            [
                'code' => 'SC06',
                'name' => 'Beast Party',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SC06_EN.png',
            ],
            [
                'code' => 'SB63',
                'name' => 'Bingo Slot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB63_EN.png',
            ],
            [
                'code' => 'SB59',
                'name' => 'Kung Fu All Stars',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB59_EN.png',
            ],
            [
                'code' => 'WH52',
                'name' => 'Bao Zu Po',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH52_EN.png',
            ],
            [
                'code' => 'WH62',
                'name' => 'Sex and Zen',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH62_EN.png',
            ],
            [
                'code' => 'SB60',
                'name' => 'Ace Heist',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB60_EN.png',
            ],
            [
                'code' => 'WH31',
                'name' => 'Golden Dragon',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH31_EN.png',
            ],
            [
                'code' => 'WH49',
                'name' => 'Lucha Heroes',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH49_EN.png',
            ],
            [
                'code' => 'WH25',
                'name' => 'The Nutcracker',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH25_EN.png',
            ],
            [
                'code' => 'WH65',
                'name' => 'Temple Raider',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH65_EN.png',
            ],
            [
                'code' => 'SB56',
                'name' => 'Vegas Vegas',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB56_EN.png',
            ],
            [
                'code' => 'WH54',
                'name' => 'Ultra Shift',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH54_EN.png',
            ],
            [
                'code' => 'WH26',
                'name' => 'Sushi Nights',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH26_EN.png',
            ],
            [
                'code' => 'WH40',
                'name' => 'Peking Opera',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH40_EN.png',
            ],
            [
                'code' => 'WH44',
                'name' => 'Steampunk War',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH44_EN.png',
            ],
            [
                'code' => 'SB58',
                'name' => 'Sexy Succubus',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB58_EN.png',
            ],
            [
                'code' => 'WH36',
                'name' => 'One Percenter',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH36_EN.png',
            ],
            [
                'code' => 'WH42',
                'name' => 'Young and Dangerous',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH42_EN.png',
            ],
            [
                'code' => 'WH55',
                'name' => 'Money Monster',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH55_EN.png',
            ],
            [
                'code' => 'SB57',
                'name' => 'Evil Dragons',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB57_EN.png',
            ],
            [
                'code' => 'WH19',
                'name' => 'Treasure Tarot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH19_EN.png',
            ],
            [
                'code' => 'WH28',
                'name' => 'Egyptian Treasure',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH28_EN.png',
            ],
            [
                'code' => 'WH27',
                'name' => 'Kabuki Gold',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH27_EN.png',
            ],
            [
                'code' => 'WH30',
                'name' => 'Fortune Alchemy',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH30_EN.png',
            ],
            [
                'code' => 'WH23',
                'name' => 'Fengshen Yanyi',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH23_EN.png',
            ],
            [
                'code' => 'WH07',
                'name' => 'Festival Lions',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH07_EN.png',
            ],
            [
                'code' => 'WH02',
                'name' => 'Joan of Arc',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH02_EN.png',
            ],
            [
                'code' => 'WH12',
                'name' => "Panda's Gold",
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH12_EN.png',
            ],
            [
                'code' => 'WH35',
                'name' => 'Koi Treasure',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH35_EN.png',
            ],
            [
                'code' => 'WH38',
                'name' => 'Chinese Zodiac',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH38_EN.png',
            ],
            [
                'code' => 'WH25',
                'name' => 'The Nutcracker',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH25_EN.png',
            ],
            [
                'code' => 'WH65',
                'name' => 'Temple Raider',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH65_EN.png',
            ],
            [
                'code' => 'SB56',
                'name' => 'Vegas Vegas',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB56_EN.png',
            ],
            [
                'code' => 'WH54',
                'name' => 'Ultra Shift',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH54_EN.png',
            ],
            [
                'code' => 'WH26',
                'name' => 'Sushi Nights',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH26_EN.png',
            ],
            [
                'code' => 'WH40',
                'name' => 'Peking Opera',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH40_EN.png',
            ],
            [
                'code' => 'WH44',
                'name' => 'Steampunk War',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH44_EN.png',
            ],
            [
                'code' => 'SB58',
                'name' => 'Sexy Succubus',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB58_EN.png',
            ],
            [
                'code' => 'WH36',
                'name' => 'One Percenter',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH36_EN.png',
            ],
            [
                'code' => 'WH42',
                'name' => 'Young and Dangerous',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH42_EN.png',
            ],
            [
                'code' => 'WH55',
                'name' => 'Money Monster',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH55_EN.png',
            ],
            [
                'code' => 'SB57',
                'name' => 'Evil Dragons',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB57_EN.png',
            ],
            [
                'code' => 'WH19',
                'name' => 'Treasure Tarot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH19_EN.png',
            ],
            [
                'code' => 'WH28',
                'name' => 'Egyptian Treasure',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH28_EN.png',
            ],
            [
                'code' => 'WH27',
                'name' => 'Kabuki Gold',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH27_EN.png',
            ],
            [
                'code' => 'WH30',
                'name' => 'Fortune Alchemy',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH30_EN.png',
            ],
            [
                'code' => 'WH23',
                'name' => 'Fengshen Yanyi',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH23_EN.png',
            ],
            [
                'code' => 'WH07',
                'name' => 'Festival Lions',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH07_EN.png',
            ],
            [
                'code' => 'WH02',
                'name' => 'Joan of Arc',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH02_EN.png',
            ],
            [
                'code' => 'WH12',
                'name' => "Panda's Gold",
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH12_EN.png',
            ],
            [
                'code' => 'WH35',
                'name' => 'Koi Treasure',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH35_EN.png',
            ],
            [
                'code' => 'WH38',
                'name' => 'Chinese Zodiac',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH38_EN.png',
            ],
            [
                'code' => 'WH20',
                'name' => 'Huluwa',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH20_EN.png',
            ],
            [
                'code' => 'WH32',
                'name' => 'TanWanLanYue',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH32_EN.png',
            ],
            [
                'code' => 'WH34',
                'name' => 'Touchdown Hottie',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH34_EN.png',
            ],
            [
                'code' => 'WH18',
                'name' => 'Snow White',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH18_EN.png',
            ],
            [
                'code' => 'SB55',
                'name' => 'Lucky Combo',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB55_EN.png',
            ],
            [
                'code' => 'WC01',
                'name' => 'Happy Jump',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WC01_EN.png',
            ],
            [
                'code' => 'WH24',
                'name' => 'The Living Dead',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH24_EN.png',
            ],
            [
                'code' => 'WH21',
                'name' => 'Bloody Kisses',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH21_EN.png',
            ],
            [
                'code' => 'WH29',
                'name' => "Witch's Quest",
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH29_EN.png',
            ],
            [
                'code' => 'WH22',
                'name' => 'Dark Joker',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH22_EN.png',
            ],
            [
                'code' => 'SC05',
                'name' => 'Wild 777',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SC05_EN.png',
            ],
            [
                'code' => 'WA01',
                'name' => 'Diamond Queen',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WA01_EN.png',
            ],
            [
                'code' => 'WH17',
                'name' => 'The Moon Lady',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH17_EN.png',
            ],
            [
                'code' => 'WH10',
                'name' => "Alice's Adventures",
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH10_EN.png',
            ],
            [
                'code' => 'WH11',
                'name' => 'The Storm',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH11_EN.png',
            ],
            [
                'code' => 'WH06',
                'name' => 'King Arthur',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH06_EN.png',
            ],
            [
                'code' => 'WH04',
                'name' => 'Mucha Goddesses',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH04_EN.png',
            ],
            [
                'code' => 'EP02',
                'name' => 'DragonTiger',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/EP02_EN.png',
            ],
            [
                'code' => 'WH03',
                'name' => 'Real Champions',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH03_EN.png',
            ],
            [
                'code' => 'SB51',
                'name' => 'King of Glory',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB51_EN.png',
            ],
            [
                'code' => 'WH01',
                'name' => 'Alibaba',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/WH01_EN.png',
            ],
            [
                'code' => 'SB47',
                'name' => 'Mystic Gems',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB47_EN.png',
            ],
            [
                'code' => 'SB50',
                'name' => 'Mr XIN',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB50_EN.png',
            ],
            // New game data
            [
                'code' => 'SB49',
                'name' => 'The Dragon Pearl Gold',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB49_EN.png',
            ],
            [
                'code' => 'SB45',
                'name' => 'Legend of the Dragon',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB45_EN.png',
            ],
            [
                'code' => 'SC03',
                'name' => 'Gold Class',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SC03_EN.png',
            ],
            [
                'code' => 'SX02',
                'name' => 'Street Battle',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SX02_EN.png',
            ],
            [
                'code' => 'XG13',
                'name' => 'Fantasies',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG13_EN.png',
            ],
            [
                'code' => 'XG11',
                'name' => 'Moon Festival',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG11_EN.png',
            ],
            [
                'code' => 'XG12',
                'name' => 'K-Pop',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG12_EN.png',
            ],
            [
                'code' => 'XG16',
                'name' => 'Kick Off',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG16_EN.png',
            ],
            [
                'code' => 'XG10',
                'name' => 'Dragon Boat Festival',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG10_EN.png',
            ],
            [
                'code' => 'SB34',
                'name' => 'Ice Crush',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB34_EN.png',
            ],
            [
                'code' => 'SB33',
                'name' => 'Candy Quest',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB33_EN.png',
            ],
            [
                'code' => 'FRU2',
                'name' => 'Fruit Slot 2',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/FRU2_EN.png',
            ],
            [
                'code' => 'SB37',
                'name' => 'Shanghai Bund',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB37_EN.png',
            ],
            [
                'code' => 'PKBD',
                'name' => 'Deuces Wild',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/PKBD_EN.png',
            ],
            [
                'code' => 'PKBB',
                'name' => 'Bonus Deuces Wild',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/PKBB_EN.png',
            ],
            [
                'code' => 'XG01',
                'name' => 'Dragons Pearl',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG01_EN.png',
            ],
            [
                'code' => 'XG02',
                'name' => 'Lucky 8',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG02_EN.png',
            ],
            [
                'code' => 'XG03',
                'name' => 'Bling Bling',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG03_EN.png',
            ],
            [
                'code' => 'XG04',
                'name' => 'Goldfish',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG04_EN.png',
            ],
            [
                'code' => 'XG05',
                'name' => 'Chinese New Year',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG05_EN.png',
            ],
            [
                'code' => 'XG06',
                'name' => 'Pirates',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG06_EN.png',
            ],
            [
                'code' => 'XG07',
                'name' => 'Fruitmania',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG07_EN.png',
            ],

            [
                'code' => 'XG08',
                'name' => 'Red Panda',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG08_EN.png',
            ],
            [
                'code' => 'XG09',
                'name' => 'High Roller',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/XG09_EN.png',
            ],
            [
                'code' => 'SB30',
                'name' => 'Year of the Monkey',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB30_EN.png',
            ],
            [
                'code' => 'SB28',
                'name' => 'God of Wu Fortune',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB28_EN.png',
            ],
            [
                'code' => 'SB07',
                'name' => 'Chinese Chess Slot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB07_EN.png',
            ],
            [
                'code' => 'SB09',
                'name' => 'Chess Slot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB09_EN.png',
            ],
            [
                'code' => 'SB10',
                'name' => 'Happy Farm',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB10_EN.png',
            ],
            [
                'code' => 'SB08',
                'name' => 'Mahjong Slot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB08_EN.png',
            ],
            [
                'code' => 'SB11',
                'name' => 'Summer Campsite',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB11_EN.png',
            ],
            [
                'code' => 'SB01',
                'name' => 'Space Odyssey',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB01_EN.png',
            ],
            [
                'code' => 'SB06',
                'name' => 'Samurai',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB06_EN.png',
            ],
            [
                'code' => 'SB02',
                'name' => 'Garden Vintage',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/SB02_EN.png',
            ],
            [
                'code' => 'PKBJ',
                'name' => 'Video poker2 (jacks or better)',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/PKBJ_EN.png',
            ],
            [
                'code' => 'FRU',
                'name' => 'Fruit Slot',
                'game_type_id' => 1,
                'product_id' => 1,
                'image_url' => 'http://prodmd.9977997.com/Image/AsiaGaming/en/FRU_EN.png',
            ],

        ];

        foreach ($data as $game) {
            GameList::create($game);
        }
    }
}
