<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PGSoftGameListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'code' => '1',
                'name' => 'Honey Trap of Diao Chan',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/1.png',
            ],
            [
                'code' => '2',
                'name' => 'Gem Saviour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/2.png',
            ],
            [
                'code' => '3',
                'name' => 'Fortune Gods',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/3.png',
            ],
            [
                'code' => '6',
                'name' => 'Medusa 2: The Quest of Perseus',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/6.png',
            ],
            [
                'code' => '7',
                'name' => 'Medusa 1: The Curse of Athena',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/7.png',
            ],
            [
                'code' => '18',
                'name' => 'Hood vs Wolf',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/18.png',
            ],
            [
                'code' => '20',
                'name' => 'Reel Love',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/20.png',
            ],
            [
                'code' => '24',
                'name' => 'Win Win Won',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/24.png',
            ],
            [
                'code' => '25',
                'name' => 'Plushie Frenzy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/25.png',
            ],
            [
                'code' => '26',
                'name' => 'Tree of Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/26.png',
            ],
            [
                'code' => '28',
                'name' => 'Hotpot',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/28.png',
            ],
            [
                'code' => '29',
                'name' => 'Dragon Legend',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/29.png',
            ],
            [
                'code' => '33',
                'name' => 'Hip Hop Panda',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/33.png',
            ],
            [
                'code' => '34',
                'name' => 'Legend of Hou Yi',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/34.png',
            ],
            [
                'code' => '35',
                'name' => 'Mr. Hallow-Win',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/35.png',
            ],
            [
                'code' => '36',
                'name' => 'Prosperity Lion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/36.png',
            ],
            [
                'code' => '37',
                'name' => 'Santa\'s Gift Rush',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/37.png',
            ],
            [
                'code' => '1',
                'name' => 'Honey Trap of Diao Chan',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/1.png',
            ],
            [
                'code' => '2',
                'name' => 'Gem Saviour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/2.png',
            ],
            [
                'code' => '3',
                'name' => 'Fortune Gods',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/3.png',
            ],
            [
                'code' => '6',
                'name' => 'Medusa 2: The Quest of Perseus',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/6.png',
            ],
            [
                'code' => '7',
                'name' => 'Medusa 1: The Curse of Athena',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/7.png',
            ],
            [
                'code' => '18',
                'name' => 'Hood vs Wolf',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/18.png',
            ],
            [
                'code' => '20',
                'name' => 'Reel Love',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/20.png',
            ],
            [
                'code' => '24',
                'name' => 'Win Win Won',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/24.png',
            ],
            [
                'code' => '25',
                'name' => 'Plushie Frenzy',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/25.png',
            ],
            [
                'code' => '26',
                'name' => 'Tree of Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/26.png',
            ],
            [
                'code' => '28',
                'name' => 'Hotpot',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/28.png',
            ],
            [
                'code' => '29',
                'name' => 'Dragon Legend',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/29.png',
            ],
            [
                'code' => '33',
                'name' => 'Hip Hop Panda',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/33.png',
            ],
            [
                'code' => '34',
                'name' => 'Legend of Hou Yi',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/34.png',
            ],
            [
                'code' => '35',
                'name' => 'Mr. Hallow-Win',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/35.png',
            ],
            [
                'code' => '36',
                'name' => 'Prosperity Lion',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/36.png',
            ],
            [
                'code' => '37',
                'name' => 'Santa\'s Gift Rush',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/37.png',
            ],
            [
                'code' => '38',
                'name' => 'Gem Saviour Sword',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/38.png',
            ],
            [
                'code' => '39',
                'name' => 'Piggy Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/39.png',
            ],
            [
                'code' => '40',
                'name' => 'Jungle Delight',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/40.png',
            ],
            [
                'code' => '41',
                'name' => 'Symbols Of Egypt',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/41.png',
            ],
            [
                'code' => '42',
                'name' => 'Ganesha Gold',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/42.png',
            ],
            [
                'code' => '44',
                'name' => 'Emperor\'s Favour',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/44.png',
            ],
            [
                'code' => '48',
                'name' => 'Double Fortune',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/48.png',
            ],
            [
                'code' => '50',
                'name' => 'Journey to the Wealth',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/50.png',
            ],
            [
                'code' => '53',
                'name' => 'The Great Icescape',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/53.png',
            ],
            [
                'code' => '54',
                'name' => 'Captain\'s Bounty',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/54.png',
            ],
            [
                'code' => '57',
                'name' => 'Dragon Hatch',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/57.png',
            ],
            [
                'code' => '58',
                'name' => 'Vampire\'s Charm',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/58.png',
            ],
            [
                'code' => '59',
                'name' => 'Ninja vs Samurai',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/59.png',
            ],
            [
                'code' => '60',
                'name' => 'Leprechaun Riches',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/60.png',
            ],
            [
                'code' => '61',
                'name' => 'Flirting Scholar',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/61.png',
            ],
            [
                'code' => '62',
                'name' => 'Gem Saviour Conquest',
                'game_type_id' => 1,
                'product_id' => 31,
                'image_url' => 'http://prodmd.9977997.com/Image/PGSoft/en/62.png',
            ],
        ];

        DB::table('games')->insert($data);
    }
}
