<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RealTimeGamingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = [
            [
                'code' => '1179948',
                'name' => 'Big Santa',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BigSanta-200x200-en.jpg',
            ],
            [
                'code' => '1180008',
                'name' => 'Sweet Shop Collect',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SweetShopCollect-200x200-en.jpg',
            ],
            [
                'code' => '1180023',
                'name' => 'Toltec Gems',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ToltecGems-200x200-en.jpg',
            ],
            [
                'code' => '1179996',
                'name' => 'Fortunes of Olympus',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunesofOlympus-200x200-en.jpg',
            ],
            [
                'code' => '1179882',
                'name' => 'RTG 777',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/RTG777-200x200-en.jpg',
            ],
            [
                'code' => '1179672',
                'name' => 'Enchanted Garden',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EnchantedGarden-200x200-en.jpg',
            ],
            [
                'code' => '1179912',
                'name' => 'Bao Ni 8',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/BaoNi8-200x200-en.jpg',
            ],
            [
                'code' => '1180000',
                'name' => 'Warrior Conquest',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WarriorConquest-200x200-en.jpg',
            ],
            [
                'code' => '1179992',
                'name' => 'Goblins: Gluttony of Gems',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/GoblinsGluttonyofGems-200x200-en.jpg',
            ],
            [
                'code' => '1179881',
                'name' => 'Plentiful Treasure',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PlentifulTreasure-200x200-en.jpg',
            ],
            [
                'code' => '1179965',
                'name' => 'Sweet 16 Blast!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Sweet16Blast!-200x200-en.jpg',
            ],
            [
                'code' => '1179889',
                'name' => 'Wu Zetian',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WuZetian-200x200-en.jpg',
            ],
            [
                'code' => '1179709',
                'name' => 'Texan Tycoon',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TexanTycoon-200x200-en.jpg',
            ],
            [
                'code' => '1179830',
                'name' => 'Sweet 16',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Sweet16-200x200-en.jpg',
            ],
            [
                'code' => '1179904',
                'name' => 'Fat Cat Cafe',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FatCatCafe-200x200-en.jpg',
            ],
            [
                'code' => '1179700',
                'name' => 'T-Rex',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/T-Rex-200x200-en.jpg',
            ],
            [
                'code' => '1179847',
                'name' => 'Kung Fu Rooster',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/KungFuRooster-200x200-en.jpg',
            ],
            [
                'code' => '1179897',
                'name' => 'T-Rex II',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/T-RexII-200x200-en.jpg',
            ],
            [
                'code' => '1179803',
                'name' => 'Heavenly Treasures',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/HeavenlyTreasures-200x200-en.jpg',
            ],
            [
                'code' => '1179846',
                'name' => 'Cash Bandits 2',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CashBandits2-200x200-en.jpg',
            ],
            [
                'code' => '1179841',
                'name' => 'Dragon Orb',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/DragonOrb-200x200-en.jpg',
            ],
            [
                'code' => '1179913',
                'name' => 'Shadow Gods',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ShadowGods-200x200-en.jpg',
            ],
            [
                'code' => '1179893',
                'name' => 'Pig Winner',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PigWinner-200x200-en.jpg',
            ],
            [
                'code' => '1179979',
                'name' => 'Shelltastic Wins!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ShelltasticWins!-200x200-en.jpg',
            ],
            [
                'code' => '1179986',
                'name' => 'Neon Wheel 7s',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/NeonWheel7s-200x200-en.jpg',
            ],
            [
                'code' => '1179909',
                'name' => 'Emperor Panda',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/EmperorPanda-200x200-en.jpg',
            ],
            [
                'code' => '1179879',
                'name' => 'Cai Hong',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CaiHong-200x200-en.jpg',
            ],
            [
                'code' => '1179987',
                'name' => 'Fortunate Rabbit',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunateRabbit-200x200-en.jpg',
            ],
            [
                'code' => '1179993',
                'name' => 'Persian Treasures',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PersianTreasures-200x200-en.jpg',
            ],
            [
                'code' => '1180009',
                'name' => 'Pharaoh Mysteries',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PharaohMysteries-200x200-en.jpg',
            ],
            [
                'code' => '1180006',
                'name' => 'Sword of the Elements',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SwordoftheElements-200x200-en.jpg',
            ],
            [
                'code' => '1179923',
                'name' => 'Wild Hog Luau',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/WildHogLuau-200x200-en.jpg',
            ],
            [
                'code' => '1179653',
                'name' => 'Goldbeard',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Goldbeard-200x200-en.jpg',
            ],
            [
                'code' => '1180003',
                'name' => 'Fortunate Zeus',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FortunateZeus-200x200-en.jpg',
            ],
            [
                'code' => '1179710',
                'name' => 'Triple Twister',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TripleTwister-200x200-en.jpg',
            ],
            [
                'code' => '1179942',
                'name' => 'Ibiza Hotpots',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/IbizaHotpots-200x200-en.jpg',
            ],
            [
                'code' => '1179905',
                'name' => 'Ape King',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ApeKing-200x200-en.jpg',
            ],
            [
                'code' => '1179698',
                'name' => 'PayDirt!',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PayDirt!-200x200-en.jpg',
            ],
            [
                'code' => '1180020',
                'name' => 'Pyramid Pets',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PyramidPets-200x200-en.jpg',
            ],
            [
                'code' => '1179895',
                'name' => 'Trigger Happy',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/TriggerHappy-200x200-en.jpg',
            ],
            [
                'code' => '1179899',
                'name' => 'Storm Lords',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/StormLords-200x200-en.jpg',
            ],
            [
                'code' => '1180018',
                'name' => 'Medieval Crusades',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MedievalCrusades-200x200-en.jpg',
            ],
            [
                'code' => '1180010',
                'name' => 'Space Paws',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SpacePaws-200x200-en.jpg',
            ],
            [
                'code' => '1179843',
                'name' => 'Purrfect Pets',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/PurrfectPets-200x200-en.jpg',
            ],
            [
                'code' => '1179825',
                'name' => 'Nova 7s',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Nova7s-200x200-en.jpg',
            ],
            [
                'code' => '1179868',
                'name' => 'Fu Chi',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FuChi-200x200-en.jpg',
            ],
            [
                'code' => '1179819',
                'name' => 'Super 6',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Super6-200x200-en.jpg',
            ],
            [
                'code' => '1179989',
                'name' => 'Mermaid Royale',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/MermaidRoyale-200x200-en.jpg',
            ],
            [
                'code' => '1179837',
                'name' => 'Fucanglong',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Fucanglong-200x200-en.jpg',
            ],
            [
                'code' => '1179883',
                'name' => 'Fire Dragon',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/FireDragon-200x200-en.jpg',
            ],
            [
                'code' => '1179887',
                'name' => 'Ancient Gods',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/AncientGods-200x200-en.jpg',
            ],
            [
                'code' => '1179826',
                'name' => 'Witch\'s Brew',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/Witch\'sBrew-200x200-en.jpg',
            ],
            [
                'code' => '1179906',
                'name' => 'Lucky Rat',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/LuckyRat-200x200-en.jpg',
            ],
            [
                'code' => '1179838',
                'name' => 'Secret Symbol',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/SecretSymbol-200x200-en.jpg',
            ],
            [
                'code' => '1179885',
                'name' => 'Three Kingdom Wars',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/ThreeKingdomWars-200x200-en.jpg',
            ],
            [
                'code' => '1179675',
                'name' => 'Crystal Waters',
                'game_type_id' => 1,
                'product_id' => 34,
                'image_url' => 'http://prodmd.9977997.com/Image/RTG/en/CrystalWaters-200x200-en.jpg',
            ],
        ];


    }
}
